export const DEFAULT_CONFIG = {
  surveyTitle: "Survei Kebutuhan Bangkom Pegawai Deputi I LAN RI",
  intro: "Survei ini bertujuan memetakan kesenjangan kompetensi dan kebutuhan pelatihan berbasis 8 Pilar Subject Matter Expert (SME) di lingkungan Deputi Bidang Peningkatan Kualitas Kebijakan Administrasi Negara.",
  competencies: [
    ["Analisis Kebijakan Isu-Isu Strategis Pemerintah dan LAN", "Pilar 2: Analisis Isu Strategis"],
    ["Metodologi Riset Kebijakan & Regulatory Impact Analysis (RIA/CBA)", "Pilar 2: Metodologi & Riset"],
    ["Quality Control (QC) & Standarisasi Produk Kebijakan / Survei", "Pilar 3: Quality Control Produk"],
    ["Pengukuran & Penerapan Indeks Kualitas Kebijakan (IKK)", "Pilar 3: Instrumen IKK LAN RI"],
    ["Penyusunan Naskah Kebijakan Berdampak Tinggi (Policy Brief / Paper / Memo)", "Pilar 3 & 4: Naskah Kebijakan"],
    ["Penulisan Artikel Ilmiah & Publikasi Jurnal Bereputasi", "Pilar 4: Publikasi Ilmiah"],
    ["Pengelolaan Manajemen Pengetahuan (Knowledge Management / KMS)", "Pilar 5: Manajemen Pengetahuan"],
    ["Pembuatan Konten Pembelajaran Digital (Microlearning / Infografis / Video)", "Pilar 6: Konten Pembelajaran"],
    ["Advokasi, Negosiasi, & Pengembangan Kerjasama Kemitraan K/L/D", "Pilar 7: Pengembangan Kerjasama"],
    ["Desain & Fasilitasi Inovasi Tata Kelola Pemerintahan Sektor Publik", "Pilar 8: Inovasi Kebijakan"],
    ["Pemanfaatan AI Generatif & Analisis Data untuk Sintesis Regulasi", "Emerging Tech / Digital Tools"],
  ].map(([title, pilar], i) => ({ id: i + 1, title, pilar })),
  smeActivities: [
    ["Sesi Sharing Knowledge & Diskusi Pakar", "Diskusi santai bedah isu aktual/regulasi baru bersama SME internal."],
    ["Bedah Buku / Literature Review Terkini", "Membahas buku rujukan kebijakan dan administrasi negara terbaru."],
    ["Klinik Coaching & Mentoring Intensif", "Pendampingan teknis intensif 1-on-1 atau tim kerja per topik spesifik."],
    ["Klinik Quality Control (QC) & Review Naskah", "Praktik membedah draf policy paper/brief untuk peningkatan kualitas."],
    ["Writing Camp & Co-Authoring Publikasi", "Pendampingan menulis artikel jurnal terakreditasi / opini media massa."],
    ["Workshop Pembuatan Konten Microlearning", "Praktik membuat modul ringkas, infografis, atau video edukasi kebijakan."],
    ["Inovasi & Policy Hackathon", "Penyelesaian tantangan nyata perumusan & advokasi kebijakan publik."],
  ].map(([title, desc], i) => ({ id: i + 1, title, desc })),
  smeTopics: [
    "Analisis Kebijakan Isu-Isu Strategis Pemerintah & LAN RI",
    "Metodologi & Standarisasi Quality Control Produk Analisis Kebijakan",
    "Teknik Penyusunan Naskah Kebijakan Berdampak Tinggi (High-Impact Policy)",
    "Strategi Penulisan Jurnal Internasional & Publikasi Bereputasi",
    "Pengembangan Konten Pembelajaran Digital & Microlearning Media",
    "Pengelolaan Manajemen Pengetahuan (Knowledge Management System)",
    "Advokasi Kebijakan & Strategi Membangun Kemitraan K/L/D",
    "Desain Laboratorium & Replikasi Inovasi Sektor Publik",
    "Pemanfaatan AI Generatif dalam Riset Regulasi & Analisis Dokumen",
  ].map((title, i) => ({ id: i + 1, title })),
};
